### PR TITLE
Adding openSUSE tumbleweed image

### PR DESCRIPTION
**Pull request by mslacken**
- sync excludes/container_exit.sh friom ob
- added tumbleweed container

### CODE REVIEW

**Comment by anderbubble** [comment]
Rebased to main.

**Comment by anderbubble** [comment]
@mslacken do you want this new image to be built and published? In which case, I'll add it to ci/cd.

Otherwise, I'll move it to the "examples" directory.

**Comment by anderbubble** [comment]
Corrected the spelling of tumbleweed in the directory.

**Review by anderbubble — COMMENTED** [review]
Looks fine to me. Just let me know if you want this to be published as an image or moved to examples.

**Comment by mslacken** [comment]
Please add as image and not example

**Review by anderbubble — APPROVED** [review]

**Pull request merged**
