### PR TITLE
Example Rocky Linux containers including the Nvidia driver

### LINKED ISSUE #31: Provide an example container image that shows how to install the Nvidia driver

### PR DESCRIPTION
**Pull request by anderbubble**
Closes #31.

### CODE REVIEW

**Comment by anderbubble** [comment]
@edvinas31 can you review these example containers? I don't have a relevant GPU node spun up to test on right now; but these appear to install and build the nvidia driver appropriately.

Let me know if you need help building containers from the PR.

**Comment by anderbubble** [comment]
@brianphan I'd also be interested in your thoughts on these.

**Comment by edvinas31** [comment]
Hi, I already solved nvidia driver installation using rc.d. I did use separate overlay for gpu node and put nvidia runtime file installation script inside rc.d for that overlay. And it is working. I am not sure how should the steps you wrote here work, because in my case I have only one gpu compute node and my headnode does not have gpu

**Comment by anderbubble** [comment]
@edvinas31 sorry for not responding earlier.

Using this method, your head node does not need to have a gpu. You can just build this image, which builds the GPU driver against the installed kernel within the image, and then serve it to GPU-equipped compute nodes. Even if you serve it to a non-GPU compute node it will still work--the GPU driver just doesn't get loaded or used.

I've simplified this PR to just provide an example for RL9, and also slightly simplified the Containerfile, too. Since it's just an example, and I've just demonstrated that it works in a test environment, I'm going to go ahead and merge it for others to see.

**Pull request merged**
